"""Generates the Now Playing Companion logo and launcher icons.

The glyph is Material Symbols Outlined "watch" (FILL 0, wght 400, GRAD 0, opsz 24) with a music
note inside the face, composed the same way Material's own "watch_check" puts a check there.
Material's "music_note" is far too tall to fit the face at a usable size, and scaling it down
thins its stem well below the font's 80-unit stroke, so the note is redrawn in the same shape
(round head, square flag) with a stem close to the surrounding stroke weight.

Outputs follow the sibling Pixel apps' conventions: #2A7FFF glyph on white, a monochrome
variant for themed icons, assets/logo.svg, and design/ PNGs for the Play Store.

Usage: python scripts/generate_icons.py   (needs numpy, Pillow, and Inkscape on PATH)
"""

import math
import shutil
import subprocess
import tempfile
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
BLUE = "#2A7FFF"

# Material Symbols Outlined "watch", viewBox 0 -960 960 960.
WATCH = (
    "M420-800h120-120Zm0 640h120-120Zm-60 80-54-182q-48-38-77-95t-29-123q0-66 29-123t77-95"
    "l54-182h240l54 182q48 38 77 95t29 123q0 66-29 123t-77 95L600-80H360Zm261.5-258.5"
    "Q680-397 680-480t-58.5-141.5Q563-680 480-680t-141.5 58.5Q280-563 280-480t58.5 141.5"
    "Q397-280 480-280t141.5-58.5ZM404-750q20-5 38.5-8t37.5-3q19 0 37.5 3t38.5 8l-16-50H420"
    "l-16 50Zm16 590h120l16-50q-20 5-38.5 7.5T480-200q-19 0-37.5-2.5T404-210l16 50Z"
)

# The watch face is a hole of radius 200 centered here. watch_check's check reaches ~171 from
# the center, leaving a ~29-unit gap to the ring; the note is sized to the same reach.
FACE_CENTER = (480.0, -480.0)
NOTE_REACH = 171.0

# Note proportions relative to the head radius (Material's music_note: stem 0.5, stem rise
# 3.5, flag 1.0 x 1.0). Stem is thickened and shortened so it can stay bold inside the face.
STEM_WIDTH = 0.9
STEM_RISE = 2.75
FLAG_WIDTH = 1.0
FLAG_HEIGHT = 0.9


def note_outline(r):
    """Boundary sample points of the note with its head centered on the origin."""
    w, rise, fw, fh = STEM_WIDTH * r, STEM_RISE * r, FLAG_WIDTH * r, FLAG_HEIGHT * r
    angles = np.linspace(0, 2 * math.pi, 720, endpoint=False)
    head = np.stack([r * np.cos(angles), r * np.sin(angles)], axis=1)
    corners = np.array([[r - w, -rise], [r + fw, -rise], [r + fw, -rise + fh], [r, -rise + fh]])
    return np.vstack([head, corners])


def enclosing_center(points):
    """Center of the smallest circle around the points (convex, so a shrinking search works)."""
    center = points.mean(axis=0)
    step = np.ptp(points, axis=0).max() / 4
    while step > 1e-4:
        candidates = center + step * np.array([[0, 0], [1, 0], [-1, 0], [0, 1], [0, -1],
                                               [1, 1], [1, -1], [-1, 1], [-1, -1]])
        reach = [np.linalg.norm(points - c, axis=1).max() for c in candidates]
        best = int(np.argmin(reach))
        if best == 0:
            step /= 2
        center = candidates[best]
    return center, np.linalg.norm(points - center, axis=1).max()


def note_path():
    # Lay the note out at unit head radius, then scale and shift so its smallest enclosing
    # circle is centered in the watch face with radius NOTE_REACH.
    center, reach = enclosing_center(note_outline(1.0))
    k = NOTE_REACH / reach
    cx = FACE_CENTER[0] - center[0] * k
    cy = FACE_CENTER[1] - center[1] * k
    r = k
    w, rise, fw, fh = STEM_WIDTH * r, STEM_RISE * r, FLAG_WIDTH * r, FLAG_HEIGHT * r
    s = math.sqrt(r * r - (r - w) ** 2)  # Where the stem's left edge meets the head.

    def f(v):
        return f"{v:.1f}".rstrip("0").rstrip(".")

    path = (
        f"M{f(cx + r - w)},{f(cy - s)}"
        f"V{f(cy - rise)}H{f(cx + r + fw)}V{f(cy - rise + fh)}H{f(cx + r)}V{f(cy)}"
        f"A{f(r)},{f(r)} 0 1 1 {f(cx + r - w)},{f(cy - s)}Z"
    )
    print(f"note: head r={r:.1f}, stem width={w:.1f}, height={rise + r:.1f}, width={2 * r + fw:.1f}")
    return path


def svg(glyph, size=24, background=None, color=BLUE):
    bg = f'<rect x="0" y="-960" width="960" height="960" fill="{background}"/>' if background else ""
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" height="{size}px" width="{size}px" '
        f'viewBox="0 -960 960 960">{bg}<path d="{glyph}" fill="{color}"/></svg>\n'
    )


def android_vector(glyph, color, comment):
    # Same placement as Pixel Photo Slideshow: 960-unit glyph box scaled 0.5625 into a
    # 1200-unit (108dp) canvas, centered. The watch's 800-unit height matches that app's glyph.
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- {comment} Generated by scripts/generate_icons.py. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="1200"
    android:viewportHeight="1200">
    <group
        android:scaleX="0.5625"
        android:scaleY="0.5625"
        android:translateX="330"
        android:translateY="870">
        <path
            android:fillColor="{color}"
            android:pathData="{glyph}" />
    </group>
</vector>
"""


def inkscape():
    default = Path(r"C:\Program Files\Inkscape\bin\inkscape.exe")
    found = shutil.which("inkscape") or (str(default) if default.exists() else None)
    if not found:
        raise SystemExit("Inkscape not found; install it or add it to PATH.")
    return found


def render(svg_text, out, px):
    """Renders an SVG to a px-by-px PNG with Inkscape."""
    with tempfile.TemporaryDirectory() as tmp:
        src = Path(tmp) / "in.svg"
        src.write_text(svg_text, encoding="utf-8")
        subprocess.run(
            [inkscape(), str(src), "--export-type=png",
             f"--export-filename={out}", f"--export-width={px}", f"--export-height={px}"],
            check=True, capture_output=True,
        )


def padded_svg(glyph, glyph_fraction):
    # Siblings' store art: glyph's 800-unit extent spans ~54% of the image (278 of 512 px).
    view = 800 / glyph_fraction
    o = 480 - view / 2
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{o:.2f} {-480 - view / 2:.2f} '
        f'{view:.2f} {view:.2f}"><rect x="{o:.2f}" y="{-480 - view / 2:.2f}" width="{view:.2f}" '
        f'height="{view:.2f}" fill="#FFFFFF"/><path d="{glyph}" fill="{BLUE}"/></svg>\n'
    )


def main():
    glyph = WATCH + note_path()

    (ROOT / "assets").mkdir(exist_ok=True)
    (ROOT / "assets" / "logo.svg").write_text(svg(glyph), encoding="utf-8")

    for module in ("mobile", "wear"):
        res = ROOT / module / "src" / "main" / "res"
        drawable = res / "drawable"
        drawable.mkdir(parents=True, exist_ok=True)
        (drawable / "ic_launcher_foreground.xml").write_text(android_vector(
            glyph, "#FF2A7FFF", "Material Symbols \"watch\" with a music note in the face, on white."),
            encoding="utf-8")
        (drawable / "ic_launcher_monochrome.xml").write_text(android_vector(
            glyph, "#FFFFFFFF", "Same glyph as ic_launcher_foreground; tinted by the system for themed icons."),
            encoding="utf-8")

    design = ROOT / "design"
    design.mkdir(exist_ok=True)
    store_art = padded_svg(glyph, 278 / 512)
    render(store_art, design / "logo-playstore-512.png", 512)
    render(store_art, design / "logo-source.png", 2000)
    print("done")


if __name__ == "__main__":
    main()
